version: '3'
services:
  web:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
      - ./app:/app
  php:
    build:
      context: .
      dockerfile: ./docker/php-fpm/Dockerfile
    volumes:
      - ./app:/app
      - ./docker/php-fpm/custom.ini:/usr/local/etc/php/conf.d/custom.ini
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 'adminpass'
      MYSQL_USER: 'anton'
      MYSQL_PASSWORD: 'antonpass'
      MYSQL_DATABASE: 'php-basic'
    volumes:
      - mysqldata:/var/lib/mysql
    ports:
      - "3306:3306"
volumes:
  mysqldata: {}
